package stevekung.mods.moreplanets.client.renderer;

import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.item.ItemStack;
import stevekung.mods.moreplanets.client.renderer.entity.*;
import stevekung.mods.moreplanets.entity.EntityBlackHole;
import stevekung.mods.moreplanets.entity.EntityBlackHoleStorage;
import stevekung.mods.moreplanets.entity.EntitySpaceCapsule;
import stevekung.mods.moreplanets.entity.projectile.EntityLaserBullet;
import stevekung.mods.moreplanets.entity.projectile.EntitySpaceFishHook;
import stevekung.mods.moreplanets.module.planets.chalos.client.renderer.entity.*;
import stevekung.mods.moreplanets.module.planets.chalos.entity.*;
import stevekung.mods.moreplanets.module.planets.chalos.entity.projectile.EntityCheeseSpore;
import stevekung.mods.moreplanets.module.planets.chalos.entity.projectile.EntitySmallCheeseSpore;
import stevekung.mods.moreplanets.module.planets.diona.client.renderer.entity.*;
import stevekung.mods.moreplanets.module.planets.diona.entity.*;
import stevekung.mods.moreplanets.module.planets.diona.entity.projectile.EntityInfectedCrystallizeArrow;
import stevekung.mods.moreplanets.module.planets.fronos.client.render.entity.RenderBearry;
import stevekung.mods.moreplanets.module.planets.fronos.client.render.entity.RenderGiantBlueberry;
import stevekung.mods.moreplanets.module.planets.fronos.client.render.entity.RenderMarshmallow;
import stevekung.mods.moreplanets.module.planets.fronos.entity.EntityBearry;
import stevekung.mods.moreplanets.module.planets.fronos.entity.EntityGiantBlueberry;
import stevekung.mods.moreplanets.module.planets.fronos.entity.EntityMarshmallow;
import stevekung.mods.moreplanets.module.planets.nibiru.client.renderer.entity.*;
import stevekung.mods.moreplanets.module.planets.nibiru.entity.*;
import stevekung.mods.moreplanets.module.planets.nibiru.entity.projectile.*;
import stevekung.mods.moreplanets.module.planets.nibiru.entity.weather.EntityNibiruLightningBolt;
import stevekung.mods.moreplanets.module.planets.nibiru.items.NibiruItems;
import stevekung.mods.moreplanets.util.client.renderer.entity.RenderSnowballMP;
import stevekung.mods.moreplanets.util.helper.ClientRegisterHelper;

public class EntityRendererMP
{
    public static void init()
    {
        ClientRegisterHelper.registerEntityRendering(EntityAlbetiusWorm.class, RenderAlbetiusWorm.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCrystallizeWorm.class, RenderInfectedCrystallizeWorm.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCrystallizeSpider.class, RenderInfectedCrystallizeSpider.class);
        ClientRegisterHelper.registerEntityRendering(EntityTier4Rocket.class, RenderTier4Rocket.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCrystallizeTentacle.class, RenderInfectedCrystallizeTentacle.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCrystallizeSlimeBoss.class, RenderInfectedCrystallizeSlimeBoss.class);
        ClientRegisterHelper.registerEntityRendering(EntityZeliusZombie.class, RenderZeliusZombie.class);
        ClientRegisterHelper.registerEntityRendering(EntityZeliusCreeper.class, RenderZeliusCreeper.class);
        ClientRegisterHelper.registerEntityRendering(EntityCheeseCubeEyeBoss.class, RenderCheeseCubeEyeBoss.class);
        ClientRegisterHelper.registerEntityRendering(EntityCheeseSpore.class, RenderCheeseSpore.class);
        ClientRegisterHelper.registerEntityRendering(EntitySmallCheeseSpore.class, RenderSmallCheeseSpore.class);
        ClientRegisterHelper.registerEntityRendering(EntityCheeseFloater.class, RenderCheeseFloater.class);
        ClientRegisterHelper.registerEntityRendering(EntityCheeseSlime.class, RenderCheeseSlime.class);
        ClientRegisterHelper.registerEntityRendering(EntityCheeseCow.class, RenderCheeseCow.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCrystallizeBomb.class, RenderInfectedCrystallizeBomb.class);
        ClientRegisterHelper.registerEntityRendering(EntityTier5Rocket.class, RenderTier5Rocket.class);
        ClientRegisterHelper.registerEntityRendering(EntityGiantWorm.class, RenderGiantWorm.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedZombie.class, RenderInfectedZombie.class);
        ClientRegisterHelper.registerEntityRendering(EntityAlienMiner.class, RenderAlienMiner.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCrystallizeSlimeMinion.class, RenderInfectedCrystallizeSlimeMinion.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedWorm.class, RenderInfectedWorm.class);
        ClientRegisterHelper.registerEntityRendering(EntityNibiruLightningBolt.class, RenderNibiruLightningBolt.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedSnowman.class, RenderInfectedSnowman.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedSnowball.class, (RenderManager manager) -> new RenderSnowballMP(manager, new ItemStack(NibiruItems.INFECTED_SNOWBALL)));
        ClientRegisterHelper.registerEntityRendering(EntityZeliusSkeleton.class, RenderZeliusSkeleton.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedGuardian.class, RenderInfectedGuardian.class);
        ClientRegisterHelper.registerEntityRendering(EntityBlackHole.class, RenderBlackHole.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedSquid.class, RenderInfectedSquid.class);
        ClientRegisterHelper.registerEntityRendering(EntityDarkLightningBolt.class, RenderDarkLightningBolt.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedEgg.class, (RenderManager manager) -> new RenderSnowballMP(manager, new ItemStack(NibiruItems.INFECTED_EGG)));
        ClientRegisterHelper.registerEntityRendering(EntityInfectedChicken.class, RenderInfectedChicken.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCrystallizeArrow.class, RenderInfectedCrystallizeArrow.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCow.class, RenderInfectedCow.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedArrow.class, RenderInfectedArrow.class);
        ClientRegisterHelper.registerEntityRendering(EntitySpaceFishHook.class, RenderSpaceFishHook.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCaveSpider.class, RenderInfectedCaveSpider.class);
        ClientRegisterHelper.registerEntityRendering(EntityAlienBeam.class, RenderAlienBeam.class);
        ClientRegisterHelper.registerEntityRendering(EntityVeinEye.class, (RenderManager manager) -> new RenderSnowballMP(manager, new ItemStack(NibiruItems.VEIN_EYE)));
        ClientRegisterHelper.registerEntityRendering(EntityShlime.class, RenderShlime.class);
        ClientRegisterHelper.registerEntityRendering(EntityLaserBullet.class, RenderLaserBullet.class);
        ClientRegisterHelper.registerEntityRendering(EntityNibiruVillager.class, RenderNibiruVillager.class);
        ClientRegisterHelper.registerEntityRendering(EntityZergius.class, RenderZergius.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedCreeper.class, RenderInfectedCreeper.class);
        ClientRegisterHelper.registerEntityRendering(EntityInfectedSkeleton.class, RenderInfectedSkeleton.class);
        ClientRegisterHelper.registerEntityRendering(EntitySpaceCapsule.class, RenderSpaceCapsule.class);
        ClientRegisterHelper.registerEntityRendering(EntityVeinFloater.class, RenderVeinFloater.class);
        ClientRegisterHelper.registerEntityRendering(EntityVeinFloaterMinion.class, RenderVeinFloaterMinion.class);
        ClientRegisterHelper.registerEntityRendering(EntityVeinBall.class, RenderVeinBall.class);
        ClientRegisterHelper.registerEntityRendering(EntityMiniVeinFloater.class, RenderMiniVeinFloater.class);
        ClientRegisterHelper.registerEntityRendering(EntityTier6Rocket.class, RenderTier6Rocket.class);
        ClientRegisterHelper.registerEntityRendering(EntityGiantBlueberry.class, RenderGiantBlueberry.class);
        ClientRegisterHelper.registerEntityRendering(EntityMarshmallow.class, RenderMarshmallow.class);
        ClientRegisterHelper.registerEntityRendering(EntityBearry.class, RenderBearry.class);
        ClientRegisterHelper.registerEntityRendering(EntityBlackHoleStorage.class, RenderBlackHoleStorage.class);
    }
}