modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/SteveKunG/MorePlanets/issues"
license = "MIT License"

[[mods]]
modId = "moreplanets"
version = "${version}"
displayName = "More Planets"
description = "An add-on adds new exotic planets into Galacticraft!"
credits = "All credits goes to Galacticraft Sources/API, Translators and some people who helped."
displayURL = "https://www.curseforge.com/minecraft/mc-mods/more-planets-gc-addon"
updateJSONURL = "https://raw.githubusercontent.com/SteveKunG/VersionCheckLibrary/master/more_planets_version.json"
authors = "SteveKunG"
logoFile = "logo.png"

[[dependencies.moreplanets]]
modId = "forge"
mandatory = true
versionRange = "[37.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreplanets]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreplanets]]
modId = "architectury"
mandatory = true
versionRange = "[2.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreplanets]]
modId = "stevekungs_lib"
mandatory = true
versionRange = "[5.0.0,)"
ordering = "NONE"
side = "BOTH"