import com.gtnewhorizons.retrofuturagradle.mcp.InjectTagsTask
import org.jetbrains.gradle.ext.Gradle
import org.codehaus.groovy.runtime.MethodClosure
import groovy.text.SimpleTemplateEngine

plugins {
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.4.1"
    id "com.gtnewhorizons.retrofuturagradle" version "1.4.6"
    id "io.github.CDAGaming.cursegradle" version "1.6.1"
    id "com.modrinth.minotaur" version "2.+"
}

ext.interpolate = this.&interpolate as MethodClosure

String interpolate(String value) {
    if (value.startsWith('${{') && value.endsWith('}}')) {
        value = value.substring(3, value.length() - 2)
        Binding newBinding = new Binding(this.binding.getVariables())
        newBinding.setProperty('it', this)
        return new GroovyShell(this.getClass().getClassLoader(), newBinding).evaluate(value)
    }
    if (value.contains('${')) {
        return new SimpleTemplateEngine().createTemplate(value).make(project.properties).toString()
    }
    return value
}

version = "${mod_version}"
group = "${maven_group}"

base {
    archivesName = archives_base_name
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
        vendor.set(JvmVendorSpec.AZUL)
    }
}

configurations {
    embed
    implementation.extendsFrom(embed)
}

minecraft {
    mcVersion.set(minecraft_version)

    mcpMappingChannel.set(mapping_channel)
    mcpMappingVersion.set(mapping_version)

    useDependencyAccessTransformers.set(true)

    if (project.hasProperty("username")) {
        username.set(project.username)
    } else {
        username.set("Developer")
    }

    // Add various JVM arguments here for runtime
    def args = ["-ea:" + group]

    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        args << "-Dmixin.debug=true"
        args << "-Dmixin.debug.verbose=true"
        args << "-Dmixin.hotSwap=true"
        args << "-Dmixin.checks.interfaces=true"
        args << "-Dmixin.debug.export=true"
        args << "-Dfml.coreMods.load=micdoodle8.mods.miccore.MicdoodlePlugin"
    }
    extraRunJvmArguments.addAll(args)

    if (file("tags.properties").exists()) {
        Properties props = new Properties().tap {  it.load(file("tags.properties").newInputStream()); it }
        if (!props.isEmpty()) {
            injectedTags.set(props.collectEntries { k, v -> [(k): interpolate(v)] })
        }
    }
}

// Adds Access Transformer files to tasks
def fileLocation = file("${projectDir}/src/main/resources/META-INF/moreplanets_at.cfg")
if (fileLocation.exists()) {
    tasks.deobfuscateMergedJarToSrg.accessTransformerFiles.from(fileLocation)
    tasks.srgifyBinpatchedJar.accessTransformerFiles.from(fileLocation)
} else {
    throw new GradleException("Access Transformer file [$fileLocation] does not exist!")
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url = "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://modmaven.dev/"
            }
        }
        filter {
            includeGroup "team.chisel.ctm"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://dvs1.progwml6.com/files/maven"
            }
        }
        filter {
            includeGroup "mezz.jei"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://maven.ic2.player.to"
            }
        }
        filter {
            includeGroup "net.industrial-craft"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://mod-buildcraft.com/maven"
            }
        }
        filter {
            includeGroup "com.mod-buildcraft"
        }
    }
    maven {
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "CleanroomMC Maven"
        url = "https://maven.cleanroommc.com"
    }
    flatDir {
        dirs "libs"
    }
    mavenLocal()
}

dependencies {
    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        String mixin = modUtils.enableMixins("zone.rong:mixinbooter:${mixin_booter_version}", "mixins.more_planets.refmap.json")
        api(mixin) {
            transitive = false
        }
        annotationProcessor "org.ow2.asm:asm-debug-all:5.2"
        annotationProcessor "com.google.guava:guava:32.1.2-jre"
        annotationProcessor "com.google.code.gson:gson:2.8.9"
        annotationProcessor(mixin) {
            transitive = false
        }
    }

    implementation(":Galacticraft-${minecraft_version}-${galacticraft_version}-deobf")

    //implementation(modUtils.deobfuscate("com.stevekung.lib:stevekung-lib:mc${minecraft_version}-v${required_stevekung_lib_version}").toString())
    implementation(modUtils.deobfuscate("curse.maven:stevekung-lib-296019:${stevekung_lib_version}").toString())

    implementation "curse.maven:hwyla-253449:2568751"
    implementation(modUtils.deobfuscate("curse.maven:codechicken-lib-1-8-242818:2779848").toString())
    implementation "mezz.jei:jei_${minecraft_version}:${jei_version}"
    implementation "curse.maven:baubles-227083:2518667"
    implementation "maven.modrinth:sound-device-options:1.0.4"
    api "curse.maven:mekanism-268560:2835176"
    api "com.mod-buildcraft:buildcraft-api:7.99.8.2"
    api "net.industrial-craft:industrialcraft-2:2.8.222-ex112:api"
    api "team.chisel.ctm:CTM:MC${minecraft_version}-${ctm_version}"
}

processResources {
    inputs.property "mod_id", mod_id
    inputs.property "mod_version", mod_version
    inputs.property "display_name", display_name
    inputs.property "required_galacticraft_version", required_galacticraft_version
    inputs.property "stevekung_lib_version", stevekung_lib_version
    inputs.property "mixin_booter_version", mixin_booter_version
}

String fileName = "${archives_base_name}-mc${minecraft_version}"

jar {
    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        manifest {
            attributes "FMLCorePlugin": "com.stevekung.moreplanets.core.MorePlanetsPlugin"
            attributes "FMLCorePluginContainsFMLMod": true
            attributes "ForceLoadAsMod": true
            attributes "FMLAT": "moreplanets_at.cfg"
        }
    }

    archiveVersion = "v${version}"
    archiveBaseName = fileName
    from sourceSets.main.output
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", mod_version
    inputs.property "mcversion", minecraft_version
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }
}

tasks.named("injectTags", InjectTagsTask).configure {
    onlyIf {
        return !it.getTags().get().isEmpty()
    }
    it.outputClassName.set("${maven_group}.core.Tags")
}

idea {
    module {
        inheritOutputDirs = true
    }
    project {
        settings {
            runConfigurations {
                "1. Run Client"(Gradle) {
                    taskNames = ["runClient"]
                }
                "2. Run Server"(Gradle) {
                    taskNames = ["runServer"]
                }
            }
            compiler.javac {
                afterEvaluate {
                    javacAdditionalOptions = "-encoding utf8"
                    moduleJavacAdditionalOptions = [
                            (project.name + ".main"): tasks.compileJava.options.compilerArgs.collect { '"' + it + '"' }.join(' ')
                    ]
                }
            }
        }
    }
}

curseforge {
    apiKey = project.hasProperty("curseforge_api_token") ? curseforge_api_token : ""
    project {
        id = curseforge_project_id
        changelog = rootProject.file("CHANGE_LOG.md")
        changelogType = "markdown"
        releaseType = release_type
        addGameVersion "Forge"
        addGameVersion minecraft_version

        if (project.hasProperty("curseforge_additional_game_versions") && !curseforge_additional_game_versions.isEmpty()) {
            curseforge_additional_game_versions.split(",").each {
                String gameVersion -> addGameVersion gameVersion
            }
        }

        mainArtifact(reobfJar) {
            it.displayName = "[Forge ${minecraft_version}] ${display_name} v${mod_version}"
        }

        if (project.hasProperty("curseforge_forge_required_dependencies") && !curseforge_forge_required_dependencies.isEmpty()
                || project.hasProperty("curseforge_forge_optional_dependencies") && !curseforge_forge_optional_dependencies.isEmpty()
                || project.hasProperty("curseforge_forge_embedded_dependencies") && !curseforge_forge_embedded_dependencies.isEmpty()
        ) {
            relations {
                if (project.hasProperty("curseforge_forge_required_dependencies") && !curseforge_forge_required_dependencies.isEmpty()) {
                    curseforge_forge_required_dependencies.split(",").each {
                        String dep -> it.requiredDependency dep
                    }
                }
                if (project.hasProperty("curseforge_forge_optional_dependencies") && !curseforge_forge_optional_dependencies.isEmpty()) {
                    curseforge_forge_optional_dependencies.split(",").each {
                        String dep -> it.optionalDependency dep
                    }
                }
                if (project.hasProperty("curseforge_forge_embedded_dependencies") && !curseforge_forge_embedded_dependencies.isEmpty()) {
                    curseforge_forge_embedded_dependencies.split(",").each {
                        String dep -> it.embeddedLibrary dep
                    }
                }
            }
        }

        afterEvaluate {
            uploadTask.dependsOn(reobfJar)
        }
    }
    options {
        debug = upload_debug.toBoolean()
        forgeGradleIntegration = false
    }
}

modrinth {
    debugMode = upload_debug.toBoolean()
    token = project.hasProperty("modrinth_api_token") ? modrinth_api_token : ""
    projectId = modrinth_project_id
    changelog = rootProject.file("CHANGE_LOG.md").text
    syncBodyFrom = rootProject.file("README.md").text
    versionName = "[Forge ${minecraft_version}] ${display_name} v${mod_version}"
    versionNumber = mod_version + "-forge"
    versionType = release_type
    uploadFile = reobfJar
    gameVersions = ["${minecraft_version}"]
    loaders = ["forge"]

    if (project.hasProperty("modrinth_additional_game_versions") && !modrinth_additional_game_versions.isEmpty()) {
        modrinth_additional_game_versions.split(",").each {
            gameVersions.add it
        }
    }

    dependencies {
        if (project.hasProperty("modrinth_forge_required_dependencies") && !modrinth_forge_required_dependencies.isEmpty()) {
            modrinth_forge_required_dependencies.split(",").each {
                required.project it
            }
        }
        if (project.hasProperty("modrinth_forge_optional_dependencies") && !modrinth_forge_optional_dependencies.isEmpty()) {
            modrinth_forge_optional_dependencies.split(",").each {
                optional.project it
            }
        }
        if (project.hasProperty("modrinth_forge_embedded_dependencies") && !modrinth_forge_embedded_dependencies.isEmpty()) {
            modrinth_forge_embedded_dependencies.split(",").each {
                embedded.project it
            }
        }
    }
}