import org.jetbrains.gradle.ext.Gradle

plugins {
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.9"
    id "com.gtnewhorizons.retrofuturagradle" version "1.4.1"
}

version = "${mod_version}"
group = "${maven_group}"

base {
    archivesName = archives_base_name
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
        // Azul covers the most platforms for Java 8 toolchains, crucially including MacOS arm64
        vendor.set(JvmVendorSpec.AZUL)
    }
}

configurations {
    embed
    implementation.extendsFrom(embed)
}

minecraft {
    mcVersion.set(minecraft_version)

    mcpMappingChannel.set(mapping_channel)
    mcpMappingVersion.set(mapping_version)

    useDependencyAccessTransformers.set(true)

    username.set("Developer")

    // Add various JVM arguments here for runtime
    def args = ["-ea:" + group]

    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        args << "-Dmixin.debug=true"
        args << "-Dmixin.debug.verbose=true"
        args << "-Dmixin.hotSwap=true"
        args << "-Dmixin.checks.interfaces=true"
        args << "-Dmixin.debug.export=true"
        args << "-Dfml.coreMods.load=micdoodle8.mods.miccore.MicdoodlePlugin"
    }
    extraRunJvmArguments.addAll(args)
}

// Adds Access Transformer files to tasks
def fileLocation = file("${projectDir}/src/main/resources/META-INF/moreplanets_at.cfg")
if (fileLocation.exists()) {
    tasks.deobfuscateMergedJarToSrg.accessTransformerFiles.from(fileLocation)
    tasks.srgifyBinpatchedJar.accessTransformerFiles.from(fileLocation)
} else {
    throw new GradleException("Access Transformer file [$fileLocation] does not exist!")
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url = "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://modmaven.dev/"
            }
        }
        filter {
            includeGroup "team.chisel.ctm"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://dvs1.progwml6.com/files/maven"
            }
        }
        filter {
            includeGroup "mezz.jei"
        }
    }
    maven {
        name = "CleanroomMC Maven"
        url = "https://maven.cleanroommc.com"
    }
    flatDir {
        dirs "libs"
    }
    mavenLocal()
}

dependencies {
    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        String mixin = modUtils.enableMixins("zone.rong:mixinbooter:${mixin_booter_version}", "mixins.${mod_id}.refmap.json")
        api(mixin) {
            transitive = false
        }
        annotationProcessor "org.ow2.asm:asm-debug-all:5.2"
        annotationProcessor "com.google.guava:guava:32.1.2-jre"
        annotationProcessor "com.google.code.gson:gson:2.8.9"
        annotationProcessor(mixin) {
            transitive = false
        }
    }

    implementation(":galacticraft-legacy:4.0.2.283")
    implementation(modUtils.deobfuscate("curse.maven:stevekungs-lib-296019:5064118").toString())
    implementation "curse.maven:hwyla-253449:2568751"
    implementation(modUtils.deobfuscate("curse.maven:codechicken-lib-1-8-242818:2779848").toString())
    api "curse.maven:baubles-227083:2518667"
    api "team.chisel.ctm:CTM:MC${minecraft_version}-${ctm_version}"
    api "mezz.jei:jei_${minecraft_version}:${jei_version}:api"
}

String fileName = "${archives_base_name}-mc${minecraft_version}"

jar {
    if (project.hasProperty("use_mixin") && use_mixin.toBoolean()) {
        manifest {
            attributes "FMLCorePlugin": "stevekung.mods.moreplanets.core.MorePlanetsPlugin"
            attributes "FMLCorePluginContainsFMLMod": true
            attributes "ForceLoadAsMod": true
        }
    }

    archiveVersion = "v${version}"
    archiveBaseName = fileName
    from sourceSets.main.output
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", mod_version
    inputs.property "mcversion", minecraft_version
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    filesMatching("pack.mcmeta") { fcd ->
        fcd.expand(
                "display_name": display_name
        )
    }

    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }
}

idea {
    module {
        inheritOutputDirs = true
    }
    project {
        settings {
            runConfigurations {
                "1. Run Client"(Gradle) {
                    taskNames = ["runClient"]
                }
                "2. Run Server"(Gradle) {
                    taskNames = ["runServer"]
                }
            }
            compiler.javac {
                afterEvaluate {
                    javacAdditionalOptions = "-encoding utf8"
                    moduleJavacAdditionalOptions = [
                            (project.name + ".main"): tasks.compileJava.options.compilerArgs.collect { '"' + it + '"' }.join(' ')
                    ]
                }
            }
        }
    }
}

tasks.register("cleanroomAfterSync") {
    // no-op
}