# gradle
use_mixin=true
upload_debug=true

# minecraft
minecraft_version=1.12.2
mapping_channel=stable
mapping_version=39

# mod
display_name=MorePlanets
archives_base_name=moreplanets
mod_id=moreplanets
mod_description=An add-on adds new exotic planets into Galacticraft!
maven_group=com.stevekung.moreplanets
mod_version=2.3.3-GC4.0.6
release_type=release
mixin_booter_version=10.6
jei_version=4.16.1.302
ctm_version=1.0.2.31

# curseforge
curseforge_project_id=923510

# modrinth
modrinth_project_id=more-planets

# forge
forge_version=14.23.5.2847