# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
use_mixin=true
upload_debug=true

# minecraft
minecraft_version=1.12.2
mapping_channel=stable
mapping_version=39

# mod
display_name=MorePlanets
archives_base_name=moreplanets
mod_id=moreplanets
mod_description=An add-on adds new exotic planets into Galacticraft!
maven_group=com.stevekung.moreplanets
mod_version=2.4.0
release_type=release
required_galacticraft_version=4.0.6
required_stevekung_lib_version=1.4.0

# dependencies
stevekung_lib_version=6773847
mixin_booter_version=10.7
galacticraft_version=4.0.7
jei_version=4.16.1.302
ctm_version=1.0.2.31

# curseforge
curseforge_project_id=261990
curseforge_forge_required_dependencies=galacticraft-legacy,mixin-booter,stevekung-lib
curseforge_forge_optional_dependencies=jei

# modrinth
modrinth_project_id=more-planets
modrinth_forge_required_dependencies=galacticraft-legacy,mixinbooter
modrinth_forge_optional_dependencies=jei