VERSION = ${mod_version}
MOD_ID = ${mod_id}
MOD_NAME = ${display_name}
GALACTICRAFT_VERSION = ${required_galacticraft_version}
STEVEKUNG_LIB_VERSION = ${required_stevekung_lib_version}
MIXIN_BOOTER_VERSION = ${mixin_booter_version}