package stevekung.mods.moreplanets.utils;

public enum EnumParticleTypesMP
{
    CRYSTALLIZED_FLAME,
    CHEESE_MILK_DRIP,
    INFECTED_SPORE,
    ALIEN_MINER_SPARK,
    INFECTED_GUARDIAN_APPEARANCE,
    DARK_PORTAL,
    ALIEN_BERRY_LEAVES,
    CUSTOM_BREAKING,
    CUSTOM_BREAKING_META,
    CUSTOM_BREAKING_MOTION,
    INFECTED_WATER_DRIP,
    CRYSTALLIZED_WATER_DRIP,
    CRYSTALLIZED_LAVA_DRIP,
    CRYSTALLIZED_LAVA,
    MC_SMOKE_LARGE,
    NUCLEAR_WASTE_DRIP,
    PURIFY_WATER_DRIP,
    KOENTUS_METEOR_SMOKE,
    CUSTOM_FALLING_DUST,
}