package stevekung.mods.moreplanets.util;

public enum EnumParticleTypesMP
{
    CRYSTALLIZE_FLAME,
    CHEESE_OF_MILK_DRIP,
    INFECTED_SPORE,
    ALIEN_MINER_SPARK,
    INFECTED_GUARDIAN_APPEARANCE,
    DARK_PORTAL,
    ALIEN_BERRY_LEAVES,
    CUSTOM_BREAKING,
    CUSTOM_BREAKING_META,
    CUSTOM_BREAKING_MOTION,
    INFECTED_WATER_DRIP,
    CRYSTALLIZE_WATER_DRIP,
    CRYSTALLIZE_LAVA_DRIP,
    CRYSTALLIZE_LAVA,
    MC_SMOKE_LARGE,
    NUCLEAR_WASTE_DRIP,
    PURIFY_WATER_DRIP,
    KOENTUS_METEOR_SMOKE,
    CUSTOM_FALLING_DUST,
}